spring:
  application:
    name: shipmentAPI

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# Logging
logging:
  level:
    root: INFO
    com:
      fedex: DEBUG

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

